version: "3"
services:
  app:
    image: atoris1192/parcel:0.1.0
    ports:
      - "1234:1234"
      - "1235:1235"
    volumes:
      - ./:/app
    working_dir: /app
    command: parcel --hmr-port 1235 --hmr-hostname localhost index.pug
    # command: parcel index.pug